name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        env:
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
          REACT_APP_WEATHER_API_URL: ${{ secrets.REACT_APP_WEATHER_API_URL }}
          REACT_APP_WEATHER_API_KEY: ${{ secrets.REACT_APP_WEATHER_API_KEY }}
          REACT_APP_HOURLY_WEATHER_API_URL: ${{ secrets.REACT_APP_HOURLY_WEATHER_API_URL }}
          REACT_APP_HOURLY_WEATHER_API_KEY: ${{ secrets.REACT_APP_HOURLY_WEATHER_API_KEY }}
        run: |
          npm install --legacy-peer-deps
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
